"use client";

// import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";

// export const metadata: Metadata = {
//   title: "Notehub",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanStackProvider>
        <body className="min-h-dvh flex flex-col">
          <Header />
          <div className="grow">
            {children}
            {modal}
          </div>
          <Footer />
        </body>
      </TanStackProvider>
    </html>
  );
}
